- name: Create user
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/bash

- name: Add user to the root group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: root
    append: yes
