---
- name: This Playbook is to create user & install git
  hosts: webservers
  become: true
  tasks:
  - name: Creating user Sylva
    user:
      name: Sylva
      state: present

  - name: Installing git
    yum:
      name: git
